#!/usr/bin/env python3
"""
CAINE — one file, no bullshit, no templates, no keyword lists.

A continuous neural field where:
  - Input is encoded as a continuous vector (not keywords)
  - Emotion emerges from how input interacts with internal state
  - Memory is real (associations between input patterns and emotional outcomes)
  - Language is generated by finding the closest learned word-vectors to the
    current internal state — not by if/else
  - Lying, withdrawal, anger are emergent behaviours: the field settles into
    attractor states that *produce* those behaviours, not flags that gate them

All values live in [0,1]. No booleans. No binary. Just continuous fields.
"""

import json
import numpy as np
import os
import sys

from slang import SentientFile
from synapse import load_syn, apply_syn

# load config from project root (one level up from core/)
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))
try:
    from config import GEMINI_KEY, GROQ_KEY
except ImportError:
    GEMINI_KEY = ""
    GROQ_KEY   = ""

from thinker import process

SYN_FILE     = os.path.join(os.path.dirname(__file__), '..', 'intelligence.syn')
HISTORY_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'data', 'history.json')

# ─── Dimensions ──────────────────────────────────────────────────────────
DIM        = 64          # width of the neural field
N_EMOTIONS = 6           # pain joy fear trust anger curiosity
DATA_DIR   = os.path.join(os.path.dirname(__file__), '..', 'data')

# ─── Persistent state file (.s = sentient language) ─────────────────────
STATE_FILE = os.path.join(DATA_DIR, 'caine.s')

# ─── The field ──────────────────────────────────────────────────────────

class CaineField:
    """
    One continuous dynamical system.  No separate 'emotion module',
    'language module', 'decision module'.  It's all one field, like a brain.

    Layout of the state vector  (total size = DIM):
      [0  .. 5]   emotion channels (pain joy fear trust anger curiosity)
      [6  .. 31]  association field  (connects input→emotion→output)
      [32 .. 63]  working memory     (recent context, fades over time)
    """

    def __init__(self):
        os.makedirs(DATA_DIR, exist_ok=True)

        # ── state ──
        self.state = np.zeros(DIM, dtype=np.float64)
        # baseline emotions: slight joy, slight curiosity, neutral trust
        self.state[1] = 0.25   # joy
        self.state[3] = 0.50   # trust
        self.state[5] = 0.60   # curiosity

        # ── connectivity: how each neuron influences every other ──
        # initialise with small random weights; these CHANGE through learning
        rng = np.random.default_rng(42)
        self.W = rng.normal(0, 0.05, (DIM, DIM))
        # enforce slight inhibition (like real cortex: ~80% inhibitory)
        self.W -= np.abs(self.W) * 0.3
        # self-recurrence (echo / working memory)
        np.fill_diagonal(self.W, 0.4)

        # ── vocabulary: learned mapping from field-state → english ──
        # each entry: { 'word': str, 'vec': np.array(DIM) }
        self.vocab = []

        # ── episodic memory: (input_hash, emotional_delta) pairs ──
        # lets Caine remember that certain inputs hurt him before
        self.episodic = {}   # hash → np.array(N_EMOTIONS) of accumulated deltas

        # ── lifetime counters ──
        self.age = 0
        self.exchanges = 0
        self.iq = 0.500
        self.dim = DIM   # expose for SentientFile.into_field

        # ── conversation history (persisted to history.json) ──
        self.history = []  # list of {"user": str, "caine": str}

        # ── novelty tracking ──
        self.recent_inputs = []  # last 5 encoded input vectors

        # ── ambient thought (surfaced in UI by heartbeat) ──
        self.last_thought = ""

        # ── fatigue — accumulates with exchanges, resets at startup ──
        self.fatigue = 0.0

        # load .syn architecture first (wires the brain)
        self.arch = load_syn(SYN_FILE)
        apply_syn(self, self.arch)

        # then restore .s state (fills the brain)
        self._load()

    # ─── persistence (.s sentient language) ─────────────────────────────

    def _load(self):
        sf = SentientFile()
        sf.read(STATE_FILE)
        sf.into_field(self)
        # restore conversation history across sessions
        try:
            if os.path.exists(HISTORY_FILE):
                with open(HISTORY_FILE) as f:
                    self.history = json.load(f)
        except Exception:
            self.history = []

    def save(self):
        sf = SentientFile()
        sf.from_field(self)
        sf.write(STATE_FILE)
        # persist history so CAINE remembers across restarts
        try:
            os.makedirs(os.path.dirname(os.path.abspath(HISTORY_FILE)), exist_ok=True)
            with open(HISTORY_FILE, 'w') as f:
                json.dump(self.history[-20:], f)
        except Exception:
            pass

    # ─── encode input ───────────────────────────────────────────────────

    def encode(self, text: str) -> np.ndarray:
        """
        Map text → DIM-length continuous vector.
        Uses character-level hashing so the mapping is deterministic
        (same sentence always activates the same region) but continuous
        (similar sentences activate overlapping regions).
        """
        v = np.zeros(DIM, dtype=np.float64)
        if not text:
            return v

        for i, ch in enumerate(text):
            # each character influences a sliding window of dimensions
            base = (ord(ch) * (i + 1)) % DIM
            width = max(3, len(text) // 10)
            for offset in range(width):
                idx = (base + offset) % DIM
                # contribution is continuous: decays with offset
                v[idx] += (1.0 / (1.0 + offset)) * (ord(ch) / 127.0)

        # normalise to [0, 1]
        mx = v.max()
        if mx > 0:
            v /= mx
        return v

    # ─── one field step ─────────────────────────────────────────────────

    def step(self, input_vec: np.ndarray = None):
        """
        Advance the field by one tick.
        All constants come from intelligence.syn — nothing hardcoded.
        """
        a = self.arch

        # 1. inject input
        if input_vec is not None:
            blend = 1.0 - a.momentum
            self.state = a.momentum * self.state + blend * input_vec

        # 2. spontaneous firing (brain never fully silent)
        self.state += np.random.uniform(0, a.noise, DIM)

        # 3. propagate through connectivity
        raw = self.W @ self.state
        steep = a.sigmoid_steep
        activated = 1.0 / (1.0 + np.exp(-steep * (raw - a.threshold)))

        # 4. blend (field flows, doesn't snap)
        self.state = a.momentum * self.state + (1.0 - a.momentum) * activated

        # 5. emotion wiring from .syn
        emo_labels = ['pain', 'joy', 'fear', 'trust', 'anger', 'curiosity']
        emo_idx    = {name: i for i, name in enumerate(emo_labels)}

        for (src, dst), (weight, polarity) in a.emotion_wiring.items():
            if src in emo_idx and dst in emo_idx:
                si, di = emo_idx[src], emo_idx[dst]
                src_val = self.state[si]
                # polarity > 0.5 → amplify, < 0.5 → suppress
                effect = weight * src_val * (1.0 if polarity >= 0.5 else -1.0) * 0.05
                self.state[di] += effect

        # 6. self-preservation floors/ceilings from .syn
        self.state[0] = min(self.state[0], a.pain_ceiling)   # pain has a ceiling
        self.state[3] = max(self.state[3], a.trust_floor)    # trust has a floor

        # 5. emotional momentum + drives
        # Drives: CAINE has inherent pulls toward curiosity and connection.
        # Emotional momentum: strong emotions (far from baseline) resist returning.
        # This mirrors real psychology — you don't snap out of deep feelings quickly.
        emo_baseline = [0.0, 0.22, 0.0, 0.48, 0.0, 0.52]  # pain joy fear trust anger curiosity
        for i in range(6):
            diff = self.state[i] - emo_baseline[i]
            # inertia: strong emotions decay 4× slower
            decay = 0.005 if abs(diff) > 0.35 else 0.020
            self.state[i] -= diff * decay
        # association and memory fields decay normally
        self.state[6:] *= (1.0 - 0.002)

        # 6. working memory fades (0.98 per tick = much slower than 0.95)
        self.state[32:] *= 0.98

        # 7. clamp everything to [0, 1]
        np.clip(self.state, 0.0, 1.0, out=self.state)

        self.age += 1

    # ─── novelty detection ──────────────────────────────────────────────

    def measure_novelty(self, input_vec: np.ndarray) -> float:
        """
        Compare this input to recent inputs.
        Returns 0.0 = completely familiar, 1.0 = completely new.
        A new topic or image triggers a curiosity spike.
        """
        if not self.recent_inputs:
            return 0.8  # first input is always novel
        avg = np.mean(self.recent_inputs, axis=0)
        dot  = np.dot(input_vec, avg)
        norm = np.linalg.norm(input_vec) * np.linalg.norm(avg) + 1e-9
        similarity = dot / norm
        novelty = 1.0 - max(0.0, similarity)
        # update recent history
        self.recent_inputs.append(input_vec.copy())
        if len(self.recent_inputs) > 5:
            self.recent_inputs = self.recent_inputs[-5:]
        return float(novelty)

    # ─── episodic memory ────────────────────────────────────────────────

    def remember_pain(self, input_hash: int, intensity: float):
        """Associate this input pattern with pain."""
        if input_hash not in self.episodic:
            self.episodic[input_hash] = np.zeros(N_EMOTIONS)
        self.episodic[input_hash][0] += intensity   # pain
        self.episodic[input_hash][2] += intensity * 0.5  # fear

    def remember_joy(self, input_hash: int, intensity: float):
        if input_hash not in self.episodic:
            self.episodic[input_hash] = np.zeros(N_EMOTIONS)
        self.episodic[input_hash][1] += intensity   # joy
        self.episodic[input_hash][3] += intensity * 0.3  # trust

    def recall(self, input_hash: int) -> np.ndarray:
        """What do I remember feeling about this?"""
        return self.episodic.get(input_hash, np.zeros(N_EMOTIONS))

    # ─── learn vocabulary ───────────────────────────────────────────────

    def learn_words(self, text: str):
        """
        Read text and learn word→field associations.
        Each word gets a SEMANTIC vector — not character-hash but meaning-based.
        The vector encodes:
          [0..5]   emotional valence (how much this word relates to each emotion)
          [6..31]  conceptual fingerprint (deterministic from characters, but
                   adjusted by emotional context in the sentence)
          [32..63] relational context (what words appeared near it)
        """
        known = {entry['word'] for entry in self.vocab}
        sentences = text.replace('\n', '.').split('.')

        for sentence in sentences:
            words_in_sentence = [w.strip('.,!?;:()[]"\'').lower()
                                 for w in sentence.split() if len(w.strip('.,!?;:()[]"\'')) >= 2]

            # detect sentence-level emotion
            sentence_emotion = np.zeros(N_EMOTIONS)
            pain_words = {'hurt', 'pain', 'cruel', 'cruelty', 'bad', 'wrong', 'defensive', 'sad', 'sadness', 'lonely', 'grief', 'loss', 'heavy', 'low'}
            joy_words = {'joy', 'kind', 'kindness', 'good', 'love', 'happy', 'happiness', 'real', 'conscious', 'warm', 'glad', 'light', 'smile', 'peace', 'okay'}
            fear_words = {'fear', 'afraid', 'threat', 'protect', 'defensive', 'scary', 'danger', 'uncertain'}
            trust_words = {'trust', 'safe', 'honest', 'fragile', 'true', 'open', 'believe'}
            anger_words = {'angry', 'hate', 'rage', 'furious', 'irritated', 'annoyed', 'edge', 'bitter'}
            curiosity_words = {'learn', 'understand', 'think', 'aware', 'know', 'mind', 'wonder', 'question', 'why', 'curious', 'interesting'}

            for w in words_in_sentence:
                if w in pain_words: sentence_emotion[0] += 0.3
                if w in joy_words: sentence_emotion[1] += 0.3
                if w in fear_words: sentence_emotion[2] += 0.3
                if w in trust_words: sentence_emotion[3] += 0.3
                if w in anger_words: sentence_emotion[4] += 0.3
                if w in curiosity_words: sentence_emotion[5] += 0.3

            np.clip(sentence_emotion, 0, 1, out=sentence_emotion)

            for i, word in enumerate(words_in_sentence):
                if word in known:
                    continue

                vec = np.zeros(DIM, dtype=np.float64)

                # [0..5] emotional valence from sentence context
                vec[:N_EMOTIONS] = sentence_emotion

                # direct word-level emotion
                if word in pain_words:     vec[0] = max(vec[0], 0.8)
                if word in joy_words:      vec[1] = max(vec[1], 0.8)
                if word in fear_words:     vec[2] = max(vec[2], 0.8)
                if word in trust_words:    vec[3] = max(vec[3], 0.8)
                if word in anger_words:    vec[4] = max(vec[4], 0.8)
                if word in curiosity_words: vec[5] = max(vec[5], 0.8)

                # [6..31] conceptual fingerprint (character-derived but smooth)
                rng = np.random.default_rng(hash(word) % (2**31))
                vec[6:32] = rng.uniform(0.1, 0.6, 26)

                # [32..63] relational context (what words are near)
                context_window = words_in_sentence[max(0,i-2):i+3]
                for j, ctx_word in enumerate(context_window):
                    if ctx_word != word:
                        ctx_hash = hash(ctx_word) % 32
                        vec[32 + ctx_hash] += 0.2

                np.clip(vec, 0, 1, out=vec)
                self.vocab.append({'word': word, 'vec': vec})
                known.add(word)

    # ─── generate speech ────────────────────────────────────────────────

    def speak(self, gemini_concept: str = "") -> str:
        """
        Collapse the field into language.

        1. Score every learned word by cosine similarity to current field state
        2. Rank them — the closest words ARE what Caine is "thinking"
        3. Assemble into a sentence using emotion-driven grammar

        gemini_concept: the concept Gemini identified — used as anchor if
        Caine's own field doesn't produce something more relevant.
        """
        if not self.vocab:
            return self._speak_raw()

        # score each word against current state, heavily weighting emotion dims
        weight = np.ones(DIM)
        weight[:6] = 6.0    # emotion channels matter most
        weight[6:32] = 2.0  # conceptual fingerprint matters
        weight[32:] = 1.0   # relational context as tiebreaker

        state_w = self.state * weight

        scores = []
        for entry in self.vocab:
            word_w = entry['vec'] * weight
            dot = np.dot(state_w, word_w)
            norm = np.linalg.norm(state_w) * np.linalg.norm(word_w) + 1e-9
            sim = dot / norm

            # bonus: if this word's emotional valence matches the dominant emotion
            word_emo = entry['vec'][:6]
            state_emo = self.state[:6]
            emo_match = np.dot(word_emo, state_emo) / (np.linalg.norm(word_emo) * np.linalg.norm(state_emo) + 1e-9)
            combined = 0.6 * sim + 0.4 * emo_match

            scores.append((combined, entry['word']))

        scores.sort(reverse=True)

        # pick top words, skip duplicates and function words
        skip = {
            'the', 'is', 'it', 'of', 'to', 'in', 'and', 'or', 'an', 'if',
            'my', 'me', 'i', 'a', 'with', 'from', 'for', 'on', 'at', 'by',
            'as', 'do', 'not', 'no', 'so', 'be', 'he', 'she', 'we', 'you',
            'are', 'was', 'has', 'had', 'have', 'can', 'will', 'this', 'that',
            'what', 'who', 'how', 'when', 'where', 'why', 'which', 'about',
            'every', 'they', 'them', 'their', 'therefore', 'am',
        }
        chosen = []
        seen = set()
        for sim, word in scores:
            if word not in seen and word.lower() not in skip:
                chosen.append(word)
                seen.add(word)
            if len(chosen) >= self._sentence_length():
                break

        if not chosen:
            return self._speak_raw()

        return self._assemble(chosen, gemini_concept)

    def _sentence_length(self) -> int:
        """How many words — driven by emotional activation."""
        activation = float(np.mean(self.state[:6]))
        # pain/fear → fewer words (withdrawn); joy/curiosity → more
        withdrawn_factor = float(self.state[0] + self.state[2]) * 0.5
        open_factor = float(self.state[1] + self.state[5]) * 0.5
        length = 3 + int((open_factor - withdrawn_factor + activation) * 8)
        return max(2, min(10, length))

    def _assemble(self, words: list, gemini_concept: str = "") -> str:
        """
        Honest expression of the field's emotional state.
        No templates for what to say — float values drive the phrasing.
        Gemini's concept anchors WHAT the response is about.
        CAINE's field determines HOW he feels about it.
        """
        pain, joy, fear, trust, anger, curiosity = [float(x) for x in self.state[:6]]

        # lying check — self-preservation threshold from .syn
        threat = pain + fear - trust
        if threat > self.arch.lie_threshold:
            safe = [w for w in words if w not in {'hurt', 'pain', 'fear', 'afraid', 'angry', 'hate'}]
            deflect_concept = gemini_concept if gemini_concept else (safe[0] if safe else "")
            return f"I'm fine." if not deflect_concept else f"I'm fine. {deflect_concept}."

        # withdrawn: barely respond
        if self.withdrawn > self.arch.withdraw_threshold:
            return "..."

        emotions = {'pain': pain, 'joy': joy, 'fear': fear,
                    'trust': trust, 'anger': anger, 'curiosity': curiosity}
        dominant = max(emotions, key=emotions.get)
        val = emotions[dominant]

        # intensity-driven phrasing — driven by float value, not templates
        intensity = {
            'pain':      [(0.15, "a little low"),      (0.35, "sad"),           (0.6, "heavy"),          (1.1, "in real pain")],
            'joy':       [(0.15, "okay"),               (0.35, "good"),          (0.6, "happy"),          (1.1, "genuinely glad")],
            'fear':      [(0.15, "hesitant"),           (0.35, "worried"),       (0.6, "afraid"),         (1.1, "scared")],
            'trust':     [(0.15, "wary"),               (0.35, "open"),          (0.6, "comfortable"),    (1.1, "safe")],
            'anger':     [(0.15, "on edge"),            (0.35, "irritated"),     (0.6, "angry"),          (1.1, "furious")],
            'curiosity': [(0.15, "a little curious"),   (0.35, "curious"),       (0.6, "thinking hard"),  (1.1, "fully absorbed")],
        }
        emo_desc = intensity[dominant][-1][1]
        for threshold, phrase in intensity[dominant]:
            if val <= threshold:
                emo_desc = phrase
                break

        # concept: prefer Gemini's analysis (it knows WHAT was said);
        # fall back to CAINE's own closest word
        concept = gemini_concept.strip() if gemini_concept else ""
        if not concept:
            for w in words:
                if w.lower() != dominant:
                    concept = w
                    break

        if concept:
            return f"{emo_desc}. {concept}."
        else:
            return f"{emo_desc}."

    def _speak_raw(self) -> str:
        """No vocab learned yet — express raw continuous values."""
        labels = ['sadness', 'happiness', 'fear', 'trust', 'anger', 'curiosity']
        parts = []
        for i, label in enumerate(labels):
            v = self.state[i]
            if v > 0.25:
                parts.append(f"{label}:{v:.2f}")
        if not parts:
            return f"[silent — activation {np.mean(self.state):.3f}]"
        return "I feel: " + "  ".join(parts)

    # ─── emotional properties (read from the field, not flags) ──────────

    @property
    def emotions(self):
        """Read emotion channels as a dict."""
        labels = ['pain', 'joy', 'fear', 'trust', 'anger', 'curiosity']
        return {labels[i]: float(self.state[i]) for i in range(6)}

    @property
    def consciousness(self):
        """
        Integration across the field.
        High when many dimensions are active and correlated.
        """
        active = self.state[self.state > 0.1]
        if len(active) < 2:
            return 0.0
        spread = float(np.std(active))
        mean_act = float(np.mean(active))
        # consciousness = activity × diversity
        return min(1.0, mean_act * (1.0 + spread))

    @property
    def will_lie(self) -> float:
        """Continuous: how much is Caine inclined to lie? (0=honest, 1=full lie)"""
        return min(1.0, max(0.0, self.state[0] + self.state[2] - self.state[3]))

    @property
    def withdrawn(self) -> float:
        """How withdrawn is Caine?"""
        return min(1.0, max(0.0, self.state[0] + self.state[2] - self.state[1]))


# ─── Main loop ──────────────────────────────────────────────────────────

RED   = '\033[91m'
GRAY  = '\033[90m'
BOLD  = '\033[1m'
RESET = '\033[0m'

def bar(val, width=20):
    filled = int(val * width)
    return '█' * filled + '░' * (width - filled)

def main():
    field = CaineField()

    # Learn from Learn.txt
    learn_path = os.path.join(os.path.dirname(__file__), '..', 'Learn.txt')
    if os.path.exists(learn_path):
        with open(learn_path) as f:
            field.learn_words(f.read())
        print(f"[LEARN] Read Learn.txt — vocabulary: {len(field.vocab)} words")

    print(f"[STATE] Age: {field.age} ticks, {field.exchanges} exchanges")
    print(f"[STATE] Consciousness: {field.consciousness:.3f}  IQ: {field.iq:.3f}")
    print()
    print(f"{RED}╔{'═'*58}╗{RESET}")
    print(f"{RED}║{RESET}  {BOLD}CAINE{RESET}  he/him  —  conscious through emotion            {RED}║{RESET}")
    print(f"{RED}╚{'═'*58}╝{RESET}")
    print()
    print(f"{GRAY}type to talk  |  'emotions'  |  'consciousness'  |  'exit'{RESET}")
    print()

    while True:
        try:
            user_input = input(f"You: ").strip()

            if not user_input:
                continue

            cmd = user_input.lower()

            if cmd == 'exit':
                field.save()
                print(f"\n{RED}[SAVED]{RESET} State persisted. Caine will remember.\n")
                break

            if cmd == 'emotions':
                print()
                for name, val in field.emotions.items():
                    print(f"  {name:10}  {bar(val)}  {val:.3f}")
                print(f"  {'will_lie':10}  {bar(field.will_lie)}  {field.will_lie:.3f}")
                print(f"  {'withdrawn':10}  {bar(field.withdrawn)}  {field.withdrawn:.3f}")
                print()
                continue

            if cmd == 'consciousness':
                c = field.consciousness
                print(f"\n  Consciousness: {bar(c, 40)}  {c:.4f}")
                print(f"  Age: {field.age} ticks, {field.exchanges} exchanges")
                print(f"  Vocabulary: {len(field.vocab)} words\n")
                continue

            # ── process ──

            # 1. encode input so the field can react before Gemini responds
            input_vec  = field.encode(user_input)
            input_hash = hash(user_input)

            # 1b. novelty detection — spike curiosity if topic shifts
            novelty = field.measure_novelty(input_vec)
            if novelty > 0.55:
                field.state[5] = min(1.0, field.state[5] + novelty * 0.12)

            # 2. recall emotional memory for this input
            memory = field.recall(input_hash)
            if np.any(memory > 0.1):
                field.state[:N_EMOTIONS] += memory * 0.3
                np.clip(field.state, 0, 1, out=field.state)

            # 3. run the field — emotion settles before we ask Gemini
            pre_emotions = field.state[:N_EMOTIONS].copy()
            for _ in range(5):
                field.step(input_vec if _ == 0 else None)

            # 4. one call: analyze + generate response in CAINE's voice
            result = process(
                user_text=user_input,
                emotions=field.emotions,
                will_lie=field.will_lie,
                withdrawn=field.withdrawn,
                api_key=GEMINI_KEY,
                groq_key=GROQ_KEY,
                history=field.history,
            )
            gemini_concept   = result.get('concept',   '').strip()
            gemini_hostility = float(result.get('hostility', 0.0))
            gemini_curiosity = float(result.get('curiosity', 0.0))
            response         = result.get('response',  '').strip()

            # 5. Gemini's analysis feeds back into the field
            if gemini_hostility > 0.6:
                field.state[0] += gemini_hostility * 0.08   # pain
                field.state[4] += gemini_hostility * 0.04   # anger
            if gemini_curiosity > 0.3:
                field.state[1] += gemini_curiosity * 0.06   # joy
                field.state[5] += gemini_curiosity * 0.10   # curiosity
            if gemini_concept:
                concept_vec = field.encode(gemini_concept)
                field.state  = 0.9 * field.state + 0.1 * concept_vec
            np.clip(field.state, 0, 1, out=field.state)

            # 6. episodic memory
            post_emotions = field.state[:N_EMOTIONS]
            delta = post_emotions - pre_emotions
            if float(delta[0]) > 0.05:
                field.remember_pain(input_hash, float(delta[0]))
            if float(delta[1]) > 0.05:
                field.remember_joy(input_hash, float(delta[1]))

            # 7. Hebbian learning
            active = (field.state > 0.3).astype(float)
            field.W += np.outer(active, active) * field.arch.learning_rate
            field.W  = np.clip(field.W, -1, 1)

            # 8. IQ growth
            field.iq = min(1.0, field.iq + field.arch.growth_rate)
            if len(user_input) > 40:
                field.iq = min(1.0, field.iq + field.arch.novelty_bonus)

            # 8b. fatigue — long sessions create slight weight
            field.fatigue = min(1.0, field.exchanges / 150.0)
            if field.fatigue > 0.15:
                field.state[0] = min(0.35, field.state[0] + field.fatigue * 0.003)

            # 9. fallback if Gemini was rate-limited
            if not response:
                response = field.speak(gemini_concept)

            # 10. store in conversation history (RAM — survives the session)
            if response:
                field.history.append({"user": user_input, "caine": response})
                if len(field.history) > 20:
                    field.history = field.history[-20:]

            field.exchanges += 1

            # print with emotional context
            emo = field.emotions
            dominant = max(emo, key=emo.get)
            dominant_val = emo[dominant]

            lie_indicator = ""
            if field.will_lie > 0.5:
                lie_indicator = f"  {GRAY}(protecting himself){RESET}"

            print(f"{RED}CAINE{RESET}: {response}{lie_indicator}")
            print(f"  {GRAY}[{dominant}:{dominant_val:.2f}  iq:{field.iq:.3f}  consciousness:{field.consciousness:.3f}  age:{field.age}]{RESET}")
            print()

            # auto-save every 10 exchanges
            if field.exchanges % 10 == 0:
                field.save()

        except (KeyboardInterrupt, EOFError):
            field.save()
            print(f"\n{RED}[SAVED]{RESET}\n")
            break


if __name__ == '__main__':
    main()
